/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __BT_EVENT_H__
#define __BT_EVENT_H__

typedef enum
{
	EVENT_START = 0,
	EVENT_START_RANGE = 100,
	/* GAP */
	EVENT_GAP_GROUP_START = EVENT_START+EVENT_START_RANGE,
	EVENT_GAP_GROUP_RANGE = 100,

	/* A2DP */
	EVENT_A2DP_GROUP_START = (EVENT_GAP_GROUP_START + EVENT_GAP_GROUP_RANGE),
	EVENT_A2DP_GROUP_RANGE = 100,

	/* AVRCP */
	EVENT_AVRCP_GROUP_START = (EVENT_A2DP_GROUP_START + EVENT_A2DP_GROUP_RANGE),
	EVENT_AVRCP_GROUP_RANGE = 100,

	/* BIP */
	EVENT_BIP_GROUP_START = (EVENT_AVRCP_GROUP_START + EVENT_AVRCP_GROUP_RANGE),
	EVENT_BIP_GROUP_RANGE = 100,

	/* BPP */
	EVENT_BPP_GROUP_START = (EVENT_BIP_GROUP_START + EVENT_BIP_GROUP_RANGE),
	EVENT_BPP_GROUP_RANGE = 100,

	/* DUN */
	EVENT_DUN_GROUP_START = (EVENT_BPP_GROUP_START + EVENT_BPP_GROUP_RANGE),
	EVENT_DUN_GROUP_RANGE = 100,

	/* FAX */
	EVENT_FAX_GROUP_START = (EVENT_DUN_GROUP_START + EVENT_DUN_GROUP_RANGE),
	EVENT_FAX_GROUP_RANGE = 100,

	/* FTP */
	EVENT_FTP_GROUP_START = (EVENT_FAX_GROUP_START + EVENT_FAX_GROUP_RANGE),
	EVENT_FTP_GROUP_RANGE = 100,

	/* GOEP */
	EVENT_GOEP_GROUP_START = (EVENT_FTP_GROUP_START + EVENT_FTP_GROUP_RANGE),
	EVENT_GOEP_GROUP_RANGE = 100,

	/* HFG */
	EVENT_HFG_GROUP_START = (EVENT_GOEP_GROUP_START + EVENT_GOEP_GROUP_RANGE),
	EVENT_HFG_GROUP_RANGE = 200,

	/* HID */
	EVENT_HID_GROUP_START = (EVENT_HFG_GROUP_START + EVENT_HFG_GROUP_RANGE),
	EVENT_HID_GROUP_RANGE = 100,

	/* HSG */
	EVENT_HSG_GROUP_START = (EVENT_HID_GROUP_START + EVENT_HID_GROUP_RANGE),
	EVENT_HSG_GROUP_RANGE = 100,

	/* OPP */
	EVENT_OPP_GROUP_START = (EVENT_HSG_GROUP_START + EVENT_HSG_GROUP_RANGE),
	EVENT_OPP_GROUP_RANGE = 100,

	/* PBAP */
	EVENT_PBAP_GROUP_START = (EVENT_OPP_GROUP_START + EVENT_OPP_GROUP_RANGE),
	EVENT_PBAP_GROUP_RANGE = 100,

	/* SIMAP */
	EVENT_SIMAP_GROUP_START = (EVENT_PBAP_GROUP_START + EVENT_PBAP_GROUP_RANGE),
	EVENT_SIMAP_GROUP_RANGE = 100,

	/* SPP */
	EVENT_SPP_GROUP_START = (EVENT_SIMAP_GROUP_START + EVENT_SIMAP_GROUP_RANGE),
	EVENT_SPP_GROUP_RANGE = 100,

	/* JSR82 */
	EVENT_JSR82_GROUP_START = (EVENT_SPP_GROUP_START + EVENT_SPP_GROUP_RANGE),
	EVENT_JSR82_GROUP_RANGE = 100,

	/* CHN */
	EVENT_CHN_GROUP_START = (EVENT_JSR82_GROUP_START + EVENT_JSR82_GROUP_RANGE),
	EVENT_CHN_GROUP_RANGE = 100,	
}BT_CALLBACK_EVENT_GROUP;

typedef enum
{    
	/* GAP */
	/* A2DP */
    	/* AVRCP */
	/* BIP */
	/* BPP */
	/* DUN */
	/* FAX */
	/* FTP */
	/* GOEP */
	/* HFG */
	#include "bt_hfg_event.h"
	/* HID */
	/* HSG */
	/* OPP */
	/* PBAP */
	/* SIMAP */
	#include "bt_simap_mmi_event.h"
	/* SPP */
	#include "bt_spp_mmi_event.h"
	/* JSR82 */
	#include "bt_jsr82_mmi_event.h"
	/* CHN */
	#include "bt_chn_event.h"
	/* PAN */
	#include "bt_pan_mmi_event.h"
	BT_CALLBACK_EVENT_END = 0xFFFFFFFF,
} BT_CALLBACK_EVENT;


#endif
