/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef __BT_MAP_MMI_EVENT_H__
#define __BT_MAP_MMI_EVENT_H__

#define MAP_SERVER_ENABLE_CNF 		  0
#define MAP_SERVER_DISABLE_CNF		  1
#define MAP_SERVER_REGISTER_CNF		  2
#define MAP_SERVER_DEREGISTER_CNF 	  3 
#define MAP_SERVER_CONNECT_IND		  4 
#define MAP_SERVER_DISCONNECT_IND 	  5 
#define MAP_SERVER_DISCONNECT_CNF 	  6 
#define MAP_SERVER_SET_FOLDER 		  7 
#define MAP_SERVER_UPDATE_INBOX		  8 
#define MAP_SERVER_GET_MESSAGE_LIST	  9 
#define MAP_SERVER_GET_FOLDER_LIST	  10 
#define MAP_SERVER_GET_MESSAGE		  11 
#define MAP_SERVER_SET_NOTIFICATION	  12 
#define MAP_SERVER_SEND_REPORT_CNF	  13 
#define MAP_SERVER_AUTHORIZE_IND	  14 
#define MAP_SERVER_PUSH_MESSAGE		 15
#define MAP_SERVER_SET_MESSAGE_STATUS	16
#define MAP_SERVER_MNS_DISCONNCET_CNF   17
#define MAP_SERVER_MNS_CONNECT_CNF      18


#endif // end of __BT_MAP_MMI_EVENT_H__