
package com.mediatek.encapsulation.com.mediatek.common.featureoption;

import com.mediatek.common.featureoption.FeatureOption;
import com.mediatek.encapsulation.EncapsulationConstant;


/** This Class is generated by mediatek */

public final class EncapsulatedFeatureOption {

    /**
     * check if GEMINI is turned on or not
     */
    public static final boolean MTK_GEMINI_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_GEMINI_SUPPORT
            : true;

    /**
     * check if MTK_WAPPUSH_SUPPORT is turned on or not
     */
    public static final boolean MTK_WAPPUSH_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_WAPPUSH_SUPPORT
            : true;

    /**
     * check if MTK_VT3G324M_SUPPORT is turned on or not
     */
    public static final boolean MTK_VT3G324M_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_VT3G324M_SUPPORT
            : true;

    /**
     * check if MTK_THEMEMANAGER_APP is turned on or not
     */
    public static final boolean MTK_THEMEMANAGER_APP = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_THEMEMANAGER_APP
            : true;

    /**
     * check if MTK_DRM_APP is turned on or not
     */
    public static final boolean MTK_DRM_APP = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_DRM_APP
            : true;

    /**
     * check if MTK_GEMINI_3G_SWITCH is turned on or not
     */
    public static final boolean MTK_GEMINI_3G_SWITCH = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_GEMINI_3G_SWITCH
            : true;

    /**
     * check if MTK_BRAZIL_CUSTOMIZATION_CLARO is turned on or not
     */
    public static final boolean MTK_BRAZIL_CUSTOMIZATION_CLARO = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_BRAZIL_CUSTOMIZATION_CLARO
            : false;

    public static final boolean MTK_SEND_RR_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.MTK_SEND_RR_SUPPORT
            : true;

    public static final boolean EVDO_DT_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.EVDO_DT_SUPPORT
            : true;

}
