/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * bluetooth_simap_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file is used to
 *
 * Author:
 * -------
 * Bingyi Chen
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision: 
 * $Modtime:
 * $Log: 
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_SIMAP_MESSAGE_H__
#define __BT_SIMAP_MESSAGE_H__


	/* APP --> BT SIMAP */
#ifdef BTMTK_ON_WISE    
	MSG_ID_BT_SIMAP_ACTIVATE_REQ,
	MSG_ID_BT_SIMAP_GROUP_START = MSG_ID_BT_SIMAP_ACTIVATE_REQ,
#else
	MSG_ID_BT_SIMAP_ACTIVATE_REQ = MSG_ID_BT_SIMAP_GROUP_START,
#endif /* BTMTK_ON_WISE */                       
	MSG_ID_BT_SIMAP_DEACTIVATE_REQ,
	MSG_ID_BT_SIMAP_AUTH_RSP,
	MSG_ID_BT_SIMAP_SEND_STATUS_IND_WITH_UNAVAILABLE_REQ,
	/* MSG_ID_BT_SIMAP_DISCONNECT_REQ: This msg is used to notify BT that the user wants to close the connection */
	MSG_ID_BT_SIMAP_DISCONNECT_REQ,

	/* BT SIMAP --> APP */
	/* MSG_ID_BT_SIMAP_AUTH_REQ: This msg is used to let MMI ask the user to accept the remote connection or not */
	MSG_ID_BT_SIMAP_ACTIVATE_CNF,
	MSG_ID_BT_SIMAP_DEACTIVATE_CNF, 
	MSG_ID_BT_SIMAP_AUTH_REQ,
	MSG_ID_BT_SIMAP_CONNECT_CNF,
	MSG_ID_BT_SIMAP_CONNECT_IND,
	MSG_ID_BT_SIMAP_DISCONNECT_CNF,
	/* MSG_ID_BT_SIMAP_DISCONNECT_IND: This msg is used to notify MMI that the connection is closed */  
	MSG_ID_BT_SIMAP_DISCONNECT_IND,
	MSG_ID_BT_SIMAP_ATR_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_APDU_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_SIM_ON_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_SIM_OFF_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_SIM_RESET_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_CARD_STATUS_IND_SENT_IND, 
	MSG_ID_BT_SIMAP_CARD_READER_STATUS_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_SET_TRANSPORT_PROTOCOL_RSP_SENT_IND, 
	MSG_ID_BT_SIMAP_AUTH_REQ_TIMEOUT_RFCLOSE_IND, 
	MSG_ID_BT_SIMAP_SIM_CONNECT_FAILED_IND, 
	MSG_ID_BT_SIMAP_BT_RESET_IND,

	/* BT SIMAP -> SIM */
	MSG_ID_BT_SIM_CONNECT_REQ,
	MSG_ID_BT_SIM_RESET_REQ,
	MSG_ID_BT_SIM_APDU_REQ,
	MSG_ID_BT_SIM_DISCONNECT_REQ,
	MSG_ID_BT_SIM_POWER_OFF_REQ,

	/* SIM --> BT SIMAP */
	MSG_ID_BT_SIM_CONNECT_CNF, 
	MSG_ID_BT_SIM_RESET_CNF,
	MSG_ID_BT_SIM_APDU_CNF,
	MSG_ID_BT_SIM_DISCONNECT_CNF,
	MSG_ID_BT_SIM_POWER_OFF_CNF,  

	/* SIMAP Inject Testing */
	MSG_ID_BT_SIMAP_INJECT_MESSAGE,

	MSG_ID_BT_SIMAP_TERMINATE_SERVICE,

	MSG_ID_BT_SIMAP_GROUP_END = MSG_ID_BT_SIMAP_TERMINATE_SERVICE,


#endif	// __BT_SIMAP_MESSAGE_H__


