/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 *   Bt_map_message.h
 *
 * Project:
 * --------
 *   BT Project
 *
 * Description:
 * ------------
 *   This file contains SAP message definition for MTK Bluetooth MAP.
 *
 * Author:
 * -------
 *   Autumn Li
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision: 
 * $Modtime:
 * $Log: 
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef __BT_MAP_MESSAGE_H__
#define __BT_MAP_MESSAGE_H__

#ifdef BTMTK_ON_WISE    
    MSG_ID_BT_MAP_INTERNAL_IND,
    MSG_ID_BT_MAP_GROUP_START = MSG_ID_BT_MAP_INTERNAL_IND,
#else
    MSG_ID_BT_MAP_INTERNAL_IND = MSG_ID_BT_MAP_GROUP_START,
#endif /* BTMTK_ON_WISE */
    MSG_ID_BT_MAPS_ACTIVATE_REQ,
    MSG_ID_BT_MAPS_ACTIVATE_CNF,
    MSG_ID_BT_MAPS_DEACTIVATE_REQ,
    MSG_ID_BT_MAPS_DEACTIVATE_CNF,

    MSG_ID_BT_MAPS_REGISTER_REQ,
    MSG_ID_BT_MAPS_REGISTER_CNF,
    MSG_ID_BT_MAPS_DEREGISTER_REQ,
    MSG_ID_BT_MAPS_DEREGISTER_CNF,
    MSG_ID_BT_MAPS_AUTHORIZE_IND,
    MSG_ID_BT_MAPS_AUTHORIZE_RSP,
    MSG_ID_BT_MAPS_CONNECT_IND,
    MSG_ID_BT_MAPS_CONNECT_RSP,
    MSG_ID_BT_MAPS_DISCONNECT_REQ,
    MSG_ID_BT_MAPS_DISCONNECT_IND,
    MSG_ID_BT_MAPS_DISCONNECT_CNF,
    MSG_ID_BT_MAPS_SET_FOLDER_IND,
    MSG_ID_BT_MAPS_SET_FOLDER_RSP,
    MSG_ID_BT_MAPS_GET_FOLDER_LISTING_IND,
    MSG_ID_BT_MAPS_GET_FOLDER_LISTING_RSP,
    MSG_ID_BT_MAPS_GET_MESSAGE_LISTING_IND,
    MSG_ID_BT_MAPS_GET_MESSAGE_LISTING_RSP,
    MSG_ID_BT_MAPS_GET_MESSAGE_IND,
    MSG_ID_BT_MAPS_GET_MESSAGE_RSP,
    MSG_ID_BT_MAPS_SET_NOTIF_REGISTRATION_IND,
    MSG_ID_BT_MAPS_SET_NOTIF_REGISTRATION_RSP,
    MSG_ID_BT_MAPS_SET_MESSAGE_STATUS_IND,
    MSG_ID_BT_MAPS_SET_MESSAGE_STATUS_RSP,
    MSG_ID_BT_MAPS_PUSH_MESSAGE_IND,
    MSG_ID_BT_MAPS_PUSH_MESSAGE_RSP,
    MSG_ID_BT_MAPS_UPDATE_INBOX_IND,
    MSG_ID_BT_MAPS_UPDATE_INBOX_RSP,
    MSG_ID_BT_MAPS_MNS_CONNECT_REQ,
    MSG_ID_BT_MAPS_MNS_CONNECT_CNF,
    MSG_ID_BT_MAPS_MNS_DISCONNECT_REQ,
    MSG_ID_BT_MAPS_MNS_DISCONNECT_IND,
    MSG_ID_BT_MAPS_MNS_DISCONNECT_CNF,
    MSG_ID_BT_MAPS_MNS_SEND_EVENT_REQ,
    MSG_ID_BT_MAPS_MNS_SEND_EVENT_CNF,
    MSG_ID_BT_MAPS_ABORT_REQ,
    MSG_ID_BT_MAPS_ABORT_CNF,

    MSG_ID_BT_MAPC_ACTIVATE_REQ,
    MSG_ID_BT_MAPC_ACTIVATE_CNF,
    MSG_ID_BT_MAPC_DEACTIVATE_REQ,
    MSG_ID_BT_MAPC_DEACTIVATE_CNF,
    MSG_ID_BT_MAPC_CONNECT_REQ,
    MSG_ID_BT_MAPC_CONNECT_CNF,
    MSG_ID_BT_MAPC_DISCONNECT_REQ,
    MSG_ID_BT_MAPC_DISCONNECT_CNF,
    MSG_ID_BT_MAPC_DISCONNECT_IND,
    MSG_ID_BT_MAPC_SET_FOLDER_REQ,
    MSG_ID_BT_MAPC_SET_FOLDER_CNF,
    MSG_ID_BT_MAPC_GET_FOLDER_LISTING_SIZE_REQ,
    MSG_ID_BT_MAPC_GET_FOLDER_LISTING_SIZE_CNF,
    MSG_ID_BT_MAPC_GET_FOLDER_LISTING_REQ,
    MSG_ID_BT_MAPC_GET_FOLDER_LISTING_CNF,
    MSG_ID_BT_MAPC_GET_MESSAGE_LISTING_SIZE_REQ,
    MSG_ID_BT_MAPC_GET_MESSAGE_LISTING_SIZE_CNF,
    MSG_ID_BT_MAPC_GET_MESSAGE_LISTING_REQ,
    MSG_ID_BT_MAPC_GET_MESSAGE_LISTING_CNF,
    MSG_ID_BT_MAPC_GET_MESSAGE_REQ,
    MSG_ID_BT_MAPC_GET_MESSAGE_CNF,
    MSG_ID_BT_MAPC_SET_NOTIF_REGISTRATION_REQ,
    MSG_ID_BT_MAPC_SET_NOTIF_REGISTRATION_CNF,
    MSG_ID_BT_MAPC_SET_MESSAGE_STATUS_REQ,
    MSG_ID_BT_MAPC_SET_MESSAGE_STATUS_CNF,
    MSG_ID_BT_MAPC_PUSH_MESSAGE_REQ,
    MSG_ID_BT_MAPC_PUSH_MESSAGE_CNF,
    MSG_ID_BT_MAPC_UPDATE_INBOX_REQ,
    MSG_ID_BT_MAPC_UPDATE_INBOX_CNF,
    MSG_ID_BT_MAPC_ABORT_REQ,
    MSG_ID_BT_MAPC_ABORT_CNF,
    MSG_ID_BT_MAPC_MNS_AUTHORIZE_IND,
    MSG_ID_BT_MAPC_MNS_AUTHORIZE_RSP,
    MSG_ID_BT_MAPC_MNS_DISCONNECT_REQ,
    MSG_ID_BT_MAPC_MNS_DISCONNECT_CNF,
    MSG_ID_BT_MAPC_MNS_SEND_EVENT_IND,
    MSG_ID_BT_MAPC_MNS_SEND_EVENT_RSP,

    MSG_ID_BT_MAP_GROUP_END = MSG_ID_BT_MAPC_MNS_SEND_EVENT_RSP,

#endif  /* __BT_MAP_MESSAGE_H__ */

